stages:
  - deploy

deploy-production:
  stage: deploy
  tags:
    - runner01
  only:
    - main
  script:
    - docker compose down
    - docker compose up -d
    - echo "Deployment complete!"
