stages:
  - build-web
  - build-android

variables:
  NODE_ENV: production

build-web:
  stage: build-web
  tags:
    - runner01
  only:
    - main
  script:
    - docker compose down
    - docker compose up -d --build
    - echo "Deployment complete!"


build-android:
  stage: build-android
  tags:
    - runner01
  script:
    # Build APK inside a container
    - |
      docker run --rm \
        -v "$CI_PROJECT_DIR:/app" \
        -w /app \
        docker.iranserver.com/node:26-bullseye bash -c '
          apt-get update &&
          apt-get install -y openjdk-17-jdk wget unzip &&
          npm ci &&
          npx expo prebuild --platform android --non-interactive &&
          cd android &&
          chmod +x gradlew &&
          ./gradlew assembleRelease
        '

    - mkdir -p artifacts
    - cp android/app/build/outputs/apk/release/*.apk artifacts/

  artifacts:
    name: "apk-$CI_COMMIT_REF_SLUG-$CI_PIPELINE_ID"
    expire_in: 90 days
    paths:
      - artifacts/*.apk